import AsyncStorage from '@react-native-async-storage/async-storage';
import {Alert, Share} from 'react-native';

class ReportService {
  static STORAGE_KEY = '@safe_homecare_reports';

  // Get all reports from storage
  static async getAllReports() {
    try {
      const reportsJson = await AsyncStorage.getItem(this.STORAGE_KEY);
      return reportsJson ? JSON.parse(reportsJson) : [];
    } catch (error) {
      console.error('Error loading reports:', error);
      return [];
    }
  }

  // Save a new report
  static async saveReport(report) {
    try {
      const reports = await this.getAllReports();
      const newReport = {
        ...report,
        id: Date.now().toString(),
      };
      reports.unshift(newReport);
      await AsyncStorage.setItem(this.STORAGE_KEY, JSON.stringify(reports));
      return newReport.id;
    } catch (error) {
      console.error('Error saving report:', error);
      throw error;
    }
  }

  // Delete a report
  static async deleteReport(reportId) {
    try {
      const reports = await this.getAllReports();
      const filteredReports = reports.filter(r => r.id !== reportId);
      await AsyncStorage.setItem(
        this.STORAGE_KEY,
        JSON.stringify(filteredReports),
      );
    } catch (error) {
      console.error('Error deleting report:', error);
      throw error;
    }
  }

  // Share a report with customer
  static async shareReport(reportId) {
    try {
      const reports = await this.getAllReports();
      const report = reports.find(r => r.id === reportId);

      if (!report) {
        throw new Error('Report not found');
      }

      // Create a formatted report message
      const message = this.formatReportForSharing(report);

      // Use React Native's Share API
      const result = await Share.share({
        title: 'SAFE HOMECARE Leak Detection Report',
        message: message,
      });

      if (result.action === Share.sharedAction) {
        return true;
      }
      return false;
    } catch (error) {
      console.error('Error sharing report:', error);
      throw error;
    }
  }

  // Format report for sharing
  static formatReportForSharing(report) {
    let message = `
🏠 SAFE HOMECARE - Leak Detection Report

📋 Report: ${report.title}
📍 Location: ${report.location}
📅 Date: ${new Date(report.createdAt).toLocaleString()}
${report.leakDetected ? '⚠️ Status: LEAK DETECTED' : '✅ Status: No Leak Detected'}

📝 Description:
${report.description || 'No additional details'}

${report.photos && report.photos.length > 0 ? `📷 Photos: ${report.photos.length} attached` : ''}
${report.videos && report.videos.length > 0 ? `🎥 Videos: ${report.videos.length} attached` : ''}

---
Generated by SAFE HOMECARE App
Your complete leak detection and prevention program
    `;

    return message.trim();
  }

  // Get report by ID
  static async getReportById(reportId) {
    try {
      const reports = await this.getAllReports();
      return reports.find(r => r.id === reportId);
    } catch (error) {
      console.error('Error getting report:', error);
      return null;
    }
  }
}

export default ReportService;
